services:
  web:
    build: .  # build from Dockerfile in current directory
    links:  # link to the database container
      - mongo
    ports:
      - "3000:3000"
    # volumes:
    environment:  # set env variables
      - DB_HOST=mongodb://mongo:27017/posts
    container_name: app
    depends_on:
      - "mongo"
  mongo:
    image: mongo
    # restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
